### ISSUE TITLE
Duplicate requests

### ISSUE THREAD

**Issue by benmccann** [vikerman/rollup-plugin-hoist-import-deps#17]
I see in the Chrome debugger that resources are being requested twice after installing the plugin:

![Screenshot from 2020-06-10 14-14-05](https://user-images.githubusercontent.com/322311/84320021-ddb52f80-ab25-11ea-8772-4c33574bf9fc.png)

The three files that are being imported twice are static imports in a file that is being dynamically imported.

My code to reproduce is here:

https://github.com/benmccann/realworld/tree/hoist-imports

You can run it with:

```
npm install
npm run dev
```

Any ideas what might be happening?

**Comment by vikerman** [comment]
Thanks for the issue and repro. Will take a look.

**Comment by vikerman** [comment]
Found the issue.

The preload is done from the root path while the JS modules are served from the /client path (So the preload is downloading default HTML instead of the actual JS).

When the dynamic import references "./" it is relative to the current JS module while in link preload generated by the preload code "./" is relative to the index.html. 


Options :
- You could try using the `{method: 'import'}` option which would use a dynamic import and the paths will be correct - but your code needs to be load order independent 
- Easiest fix is an option to set the script base path (In your case it will be '/client') that can be added in the generated code.
- Some other fix that I'm not thinking of...

**Comment by LarsDenBakker** [comment]
@vikerman we can make the imports relative to the importing module:

```js
const importPath = new URL(`./${dep}`, import.meta.url).pathname;
```

but that does assume that the import path that a given module is correct relative to that importing file. I'm not 100% sure if that's the case for rollup. Although it wouldn't work for real dynamic imports then either.

**Comment by benmccann** [comment]
Tanks for investigating! An option to set the script base path sounds fine to me.

**Comment by LarsDenBakker** [comment]
Do you have a `<base href="">` in your application?

**Comment by benmccann** [comment]
It looks like there is a `<base href="/">`. This comes from the Sapper web framework and can't be changed at the moment though there have been some requests to make it optional

The app without this plugin installed is hosted at https://realworld.svelte.dev/

**Comment by vikerman** [comment]
You should be able to use {baseUrl: 'client'} to fix your issue.

**Comment by benmccann** [comment]
That's great! Thank you so much!
